service: ds-gd-tejas
provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-east-2

functions:
  guardduty-response:
    handler: handler.lambda_handler
    environment:
      dsUsername: api
      dsPassword: xgen-no-virus5!
      dsHostname: dsm.brycehawk.com
      dsPort: "443"
      enableModules: "1"
      dsIgnoreSslValidation: "1"
      slackURL: https://hooks.slack.com/services/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
